version: '3.8'

networks:
  speka-network:
    driver: bridge
    attachable: true

services:
  speka-db:
    container_name: speka-db
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./.enviroment/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - published: ${DB_PORT}
        target: 5432
    networks:
      - speka-network

volumes:
  dbdata:
    driver: local
