// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Specification is the predicate function for specification builders.
type Specification func(*sql.Selector)
