// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.redmadrobot.com/internship/backend/lim-ext/src/repository/ent/predicate"
	"git.redmadrobot.com/internship/backend/lim-ext/src/repository/ent/specification"
)

// SpecificationUpdate is the builder for updating Specification entities.
type SpecificationUpdate struct {
	config
	hooks    []Hook
	mutation *SpecificationMutation
}

// Where appends a list predicates to the SpecificationUpdate builder.
func (su *SpecificationUpdate) Where(ps ...predicate.Specification) *SpecificationUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetCreatedAt sets the "created_at" field.
func (su *SpecificationUpdate) SetCreatedAt(t time.Time) *SpecificationUpdate {
	su.mutation.SetCreatedAt(t)
	return su
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (su *SpecificationUpdate) SetNillableCreatedAt(t *time.Time) *SpecificationUpdate {
	if t != nil {
		su.SetCreatedAt(*t)
	}
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SpecificationUpdate) SetUpdatedAt(t time.Time) *SpecificationUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (su *SpecificationUpdate) SetNillableUpdatedAt(t *time.Time) *SpecificationUpdate {
	if t != nil {
		su.SetUpdatedAt(*t)
	}
	return su
}

// SetName sets the "name" field.
func (su *SpecificationUpdate) SetName(s string) *SpecificationUpdate {
	su.mutation.SetName(s)
	return su
}

// SetDescription sets the "description" field.
func (su *SpecificationUpdate) SetDescription(s string) *SpecificationUpdate {
	su.mutation.SetDescription(s)
	return su
}

// SetAuthor sets the "author" field.
func (su *SpecificationUpdate) SetAuthor(s string) *SpecificationUpdate {
	su.mutation.SetAuthor(s)
	return su
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (su *SpecificationUpdate) SetNillableAuthor(s *string) *SpecificationUpdate {
	if s != nil {
		su.SetAuthor(*s)
	}
	return su
}

// ClearAuthor clears the value of the "author" field.
func (su *SpecificationUpdate) ClearAuthor() *SpecificationUpdate {
	su.mutation.ClearAuthor()
	return su
}

// SetStatus sets the "status" field.
func (su *SpecificationUpdate) SetStatus(s specification.Status) *SpecificationUpdate {
	su.mutation.SetStatus(s)
	return su
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (su *SpecificationUpdate) SetNillableStatus(s *specification.Status) *SpecificationUpdate {
	if s != nil {
		su.SetStatus(*s)
	}
	return su
}

// SetSpec sets the "spec" field.
func (su *SpecificationUpdate) SetSpec(s []string) *SpecificationUpdate {
	su.mutation.SetSpec(s)
	return su
}

// ClearSpec clears the value of the "spec" field.
func (su *SpecificationUpdate) ClearSpec() *SpecificationUpdate {
	su.mutation.ClearSpec()
	return su
}

// Mutation returns the SpecificationMutation object of the builder.
func (su *SpecificationUpdate) Mutation() *SpecificationMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SpecificationUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		if err = su.check(); err != nil {
			return 0, err
		}
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SpecificationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = su.check(); err != nil {
				return 0, err
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SpecificationUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SpecificationUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SpecificationUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SpecificationUpdate) check() error {
	if v, ok := su.mutation.Status(); ok {
		if err := specification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf("ent: validator failed for field \"status\": %w", err)}
		}
	}
	return nil
}

func (su *SpecificationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   specification.Table,
			Columns: specification.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: specification.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: specification.FieldCreatedAt,
		})
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: specification.FieldUpdatedAt,
		})
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: specification.FieldName,
		})
	}
	if value, ok := su.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: specification.FieldDescription,
		})
	}
	if value, ok := su.mutation.Author(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: specification.FieldAuthor,
		})
	}
	if su.mutation.AuthorCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: specification.FieldAuthor,
		})
	}
	if value, ok := su.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: specification.FieldStatus,
		})
	}
	if value, ok := su.mutation.Spec(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: specification.FieldSpec,
		})
	}
	if su.mutation.SpecCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: specification.FieldSpec,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{specification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// SpecificationUpdateOne is the builder for updating a single Specification entity.
type SpecificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SpecificationMutation
}

// SetCreatedAt sets the "created_at" field.
func (suo *SpecificationUpdateOne) SetCreatedAt(t time.Time) *SpecificationUpdateOne {
	suo.mutation.SetCreatedAt(t)
	return suo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (suo *SpecificationUpdateOne) SetNillableCreatedAt(t *time.Time) *SpecificationUpdateOne {
	if t != nil {
		suo.SetCreatedAt(*t)
	}
	return suo
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SpecificationUpdateOne) SetUpdatedAt(t time.Time) *SpecificationUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (suo *SpecificationUpdateOne) SetNillableUpdatedAt(t *time.Time) *SpecificationUpdateOne {
	if t != nil {
		suo.SetUpdatedAt(*t)
	}
	return suo
}

// SetName sets the "name" field.
func (suo *SpecificationUpdateOne) SetName(s string) *SpecificationUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetDescription sets the "description" field.
func (suo *SpecificationUpdateOne) SetDescription(s string) *SpecificationUpdateOne {
	suo.mutation.SetDescription(s)
	return suo
}

// SetAuthor sets the "author" field.
func (suo *SpecificationUpdateOne) SetAuthor(s string) *SpecificationUpdateOne {
	suo.mutation.SetAuthor(s)
	return suo
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (suo *SpecificationUpdateOne) SetNillableAuthor(s *string) *SpecificationUpdateOne {
	if s != nil {
		suo.SetAuthor(*s)
	}
	return suo
}

// ClearAuthor clears the value of the "author" field.
func (suo *SpecificationUpdateOne) ClearAuthor() *SpecificationUpdateOne {
	suo.mutation.ClearAuthor()
	return suo
}

// SetStatus sets the "status" field.
func (suo *SpecificationUpdateOne) SetStatus(s specification.Status) *SpecificationUpdateOne {
	suo.mutation.SetStatus(s)
	return suo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (suo *SpecificationUpdateOne) SetNillableStatus(s *specification.Status) *SpecificationUpdateOne {
	if s != nil {
		suo.SetStatus(*s)
	}
	return suo
}

// SetSpec sets the "spec" field.
func (suo *SpecificationUpdateOne) SetSpec(s []string) *SpecificationUpdateOne {
	suo.mutation.SetSpec(s)
	return suo
}

// ClearSpec clears the value of the "spec" field.
func (suo *SpecificationUpdateOne) ClearSpec() *SpecificationUpdateOne {
	suo.mutation.ClearSpec()
	return suo
}

// Mutation returns the SpecificationMutation object of the builder.
func (suo *SpecificationUpdateOne) Mutation() *SpecificationMutation {
	return suo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SpecificationUpdateOne) Select(field string, fields ...string) *SpecificationUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Specification entity.
func (suo *SpecificationUpdateOne) Save(ctx context.Context) (*Specification, error) {
	var (
		err  error
		node *Specification
	)
	if len(suo.hooks) == 0 {
		if err = suo.check(); err != nil {
			return nil, err
		}
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SpecificationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = suo.check(); err != nil {
				return nil, err
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SpecificationUpdateOne) SaveX(ctx context.Context) *Specification {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SpecificationUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SpecificationUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SpecificationUpdateOne) check() error {
	if v, ok := suo.mutation.Status(); ok {
		if err := specification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf("ent: validator failed for field \"status\": %w", err)}
		}
	}
	return nil
}

func (suo *SpecificationUpdateOne) sqlSave(ctx context.Context) (_node *Specification, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   specification.Table,
			Columns: specification.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: specification.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Specification.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, specification.FieldID)
		for _, f := range fields {
			if !specification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != specification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: specification.FieldCreatedAt,
		})
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: specification.FieldUpdatedAt,
		})
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: specification.FieldName,
		})
	}
	if value, ok := suo.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: specification.FieldDescription,
		})
	}
	if value, ok := suo.mutation.Author(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: specification.FieldAuthor,
		})
	}
	if suo.mutation.AuthorCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: specification.FieldAuthor,
		})
	}
	if value, ok := suo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: specification.FieldStatus,
		})
	}
	if value, ok := suo.mutation.Spec(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: specification.FieldSpec,
		})
	}
	if suo.mutation.SpecCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: specification.FieldSpec,
		})
	}
	_node = &Specification{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{specification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
