// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"git.redmadrobot.com/internship/backend/lim-ext/src/repository/ent/specification"
)

// Specification is the model entity for the Specification schema.
type Specification struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Author holds the value of the "author" field.
	Author string `json:"author,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Specification) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case specification.FieldID:
			values[i] = new(sql.NullInt64)
		case specification.FieldName, specification.FieldAuthor, specification.FieldStatus:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Specification", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Specification fields.
func (s *Specification) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case specification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case specification.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		case specification.FieldAuthor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author", values[i])
			} else if value.Valid {
				s.Author = value.String
			}
		case specification.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				s.Status = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Specification.
// Note that you need to call Specification.Unwrap() before calling this method if this Specification
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Specification) Update() *SpecificationUpdateOne {
	return (&SpecificationClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the Specification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Specification) Unwrap() *Specification {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Specification is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Specification) String() string {
	var builder strings.Builder
	builder.WriteString("Specification(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", name=")
	builder.WriteString(s.Name)
	builder.WriteString(", author=")
	builder.WriteString(s.Author)
	builder.WriteString(", status=")
	builder.WriteString(s.Status)
	builder.WriteByte(')')
	return builder.String()
}

// Specifications is a parsable slice of Specification.
type Specifications []*Specification

func (s Specifications) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
