// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SpecificationsColumns holds the columns for the "specifications" table.
	SpecificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString},
		{Name: "author", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"DRAFT", "NEW"}, Default: "DRAFT"},
		{Name: "spec", Type: field.TypeJSON, Nullable: true},
	}
	// SpecificationsTable holds the schema information for the "specifications" table.
	SpecificationsTable = &schema.Table{
		Name:       "specifications",
		Columns:    SpecificationsColumns,
		PrimaryKey: []*schema.Column{SpecificationsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SpecificationsTable,
	}
)

func init() {
}
