// Code generated by entc, DO NOT EDIT.

package specification

const (
	// Label holds the string label denoting the specification type in the database.
	Label = "specification"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the specification in the database.
	Table = "specifications"
)

// Columns holds all SQL columns for specification fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldAuthor,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
